### ISSUE TITLE
[ERROR-164] Please Enroll in this course

### ISSUE THREAD

**Issue by lsergiocespedes** [nishad/udemy-dl#113]
Good and are good let me know if someone else will get this error or maybe someone knows why I get this error
[INFO-120] Trying to log in ...
[INFO-150] Login success.
[ERROR-164] Please Enroll in this course

![image](https://cloud.githubusercontent.com/assets/9311899/15973024/26a67514-2f0b-11e6-9554-e2e19aced920.png)

**Comment by egadgetjnr** [comment]
You get that error because you're not enrolled in the course

>

**Comment by tobias-p** [comment]
This program is not for illegal downloading courses, it's just for those of us, who don't have internet all the time or a bad connection to use the courses offline.

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
