### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Zombill** [nishad/udemy-dl#117]
when i try to download this course "https://www.udemy.com/aprende-node-js-facilmente/" i have this error please help me :(

Traceback (most recent call last):
  File "<string>", line 374, in <module>
  File "<string>", line 370, in main
  File "<string>", line 290, in udemy_dl
  File "<string>", line 216, in get_video_links
TypeError: string indices must be integers

**Comment by tobias-p** [comment]
could you give us the command you used for downloading (no password or user needed... just the rest)

which version of udemy-dl do you use?

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
