### ISSUE TITLE
'NoneType' object has no attribute 'group'"

### ISSUE THREAD

**Issue by bennettl** [nishad/udemy-dl#120]
Trying to download a course, ran into this error message:

[CRITICAL-407] Cannot download lecture "Classes And Objects": "'NoneType' object has no attribute 'group'"

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Comment by bennettl** [comment]
Version 0.2.1, not sure what you need for checklist and proper prefix?

**Comment by nishad** [comment]
@bennettl, there is a default template for issues, unfortunately your issue is not reported in that format, please see https://github.com/nishad/udemy-dl/issues/108 for an example.
