### ISSUE TITLE
Not working after download some files

### ISSUE THREAD

**Issue by hima948** [nishad/udemy-dl#133]
![dl-error](https://cloud.githubusercontent.com/assets/21054670/17692820/ae258b06-63bd-11e6-86eb-e86efb63f085.png)

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Comment by tobias-p** [comment]
hi, just a thought: try to download the courses to something like "c:\courses" since the path is pretty long. maybe there is the problem why you cannot donwload.
