### ISSUE TITLE
[ERROR] WinTLS: Failed to encrypt a message! Error: The specified  data could not be encrypted.

### ISSUE THREAD

**Issue by rahulroxx** [nishad/udemy-dl#150]
Please fix this issue. it says 
[ERROR] WinTLS: Failed to encrypt a message! Error: The specified
 data could not be encrypted.
(80090329)

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
