### ISSUE TITLE
Error [CRITICAL-407] Cannot download lecture "Introduction": "'NoneType' object has no attribute 'group'"

### ISSUE THREAD

**Issue by vicktor** [nishad/udemy-dl#153]
I always get error:

[CRITICAL-407] Cannot download lecture "Introduction": "'NoneType' object has no attribute 'group'"

thanks

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
