### ISSUE TITLE
the name "udemy-dl" is not recognized as the name of cmdlet

### ISSUE THREAD

**Issue by hatahetahmad** [nishad/udemy-dl#154]
![2016-10-03_21-02-50](https://cloud.githubusercontent.com/assets/22600982/19050096/5c9b04a8-89ad-11e6-8e49-09c4234608a9.png)

This Error Message appear every time i hit enter

my main purpose is to download udemy courses with course attachment and video subs

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Comment by hatahetahmad** [comment]
All right, I didn't know that

and i did other issue that describe more in this #156

**Comment by nishad** [comment]
https://github.com/nishad/udemy-dl/issues/156 is also closed due to same policy. You can request to reopen any of these issues after making sufficient changes.

**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

**Comment by hatahetahmad** [comment]
thanks, i'm editing 156 issue to be sufficient
