### ISSUE TITLE
[BUG] Couldn't download enterprise udemy url.

### ISSUE THREAD

**Issue by classbook** [nishad/udemy-dl#174]
I have an enterprise udemy credentials. I would like to download it through udemy-dl. The url looks like "https://{something}.udemy.com/courseID" it follows same url format as udemy, but it has subdomain name "something". It gives me error as "[ERROR-815] Please follow right url format.". Please help me.

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
