### ISSUE TITLE
Can't download, ERROR 1198 

### ISSUE THREAD

**Issue by MinChanSike** [nishad/udemy-dl#180]
Got issue when I try download on Windows 10.
`udemy-dl.exe -u EMAIL -p PASSWORD https://www.udemy.com/courseName/ -o "D:\OutFolder"`

```
[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 173548
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 705, in udemy_dl
  File "<string>", line 382, in get_data_links
KeyError: u'results'
None
udemy_dl returned -1
```
Thanks

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
