### ISSUE TITLE
[BUG] Download from corporate account not possible

### ISSUE THREAD

**Issue by beingamarnath** [nishad/udemy-dl#194]
Using links to lectures from corporate account is not possible. Corporate accounts looks as below.
https://CORPORATENAME.udemy.com/COURSE_NAME.

Kindly enable the possibility of using corporate account as well

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
