### ISSUE TITLE
KeyError: 'results'

### ISSUE THREAD

**Issue by ShevoPramide** [nishad/udemy-dl#200]
when i tried to download a course from udemy i got this error !!!!

> File "/usr/bin/udemy-dl", line 7, in <module>
>     main()
> File "/usr/lib/python3.6/site-packages/udemy_dl/udemy_dl.py", line 666, in udemy_dl
>     for data in get_data_links(course_id, lecture_start, lecture_end):
>   File "/usr/lib/python3.6/site-packages/udemy_dl/udemy_dl.py", line 359, in get_data_links
>     course_data_len = len(course_data['results'])
> KeyError: 'results'
>

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
