### ISSUE TITLE
[BUG] Logging in succeeds but in but throws error

### ISSUE THREAD

**Issue by vivekt** [nishad/udemy-dl#205]
C:\udemy-dl-win>udemy-dl.exe -u myAcc@yahoo.com -p myPass https://www.udemy.com/ninafochcourse

throws the following order

[INFO-884] Downloading to: C:\udemy-dl-win\ninafochcourse

[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 33949
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 705, in udemy_dl
  File "<string>", line 382, in get_data_links
KeyError: u'results'
None
udemy_dl returned -1

Please help

Thanks and regards

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
