### ISSUE TITLE
[CRITICAL-238] Skipped. Expected quality not found!

### ISSUE THREAD

**Issue by iyakexi** [nishad/udemy-dl#217]
When I down video form udemy, I got errors below:
[CRITICAL-238] Skipped. Expected quality not found!

My environment:
mac os
Anaconda 4.3.1
Python 3.6.0

I still got errors When I switch to python2 env with conda.

**Comment by Chinese1904** [comment]
https://github.com/nishad/udemy-dl/pull/209 will fix it.

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
