### ISSUE TITLE
[CRITICAL-268] Skipped. Expected quality not found!

### ISSUE THREAD

**Issue by BenBenz** [nishad/udemy-dl#219]
I have this error with pip and the lateast version of the master branch

**Comment by coderhh** [comment]
me,too

**Comment by lukesUbuntu** [comment]
i found https://github.com/nishad/udemy-dl/pull/209 fixed it for me

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
