### ISSUE TITLE
[QUESTION] Do the teachers need to enable download  button for this tool to work?

### ISSUE THREAD

**Issue by iamtekeste** [nishad/udemy-dl#225]
What it says on the title. I ask this because it worked on a course where the download option was available, but does not work for other courses where there is no download option.

**Comment by nishad** [comment]
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.
