### ISSUE TITLE
[PROPOSAL] Update README for OS X

### ISSUE THREAD

**Issue by LukasBombach** [nishad/udemy-dl#46]
In OS X you need to sudo installing udemy-dl or you run into a cryptic error that is difficult to decipher or google:

```
sudo pip install udemy-dl
```

Also you need to sudo installing pip itself or you run into the same problem. Maybe pointing that out is a help for OS X users.

**Comment by mukhlesur-millon** [comment]
it is also applicable for linux unless you are a root user.

**Comment by nishad** [comment]
I was not in support of unnecessary use of `sudo`ed pip. However, your proposal is valid, and I made some changes in readme with https://github.com/nishad/udemy-dl/commit/8be599a7e559e4cf27e64480bfa4c538e4927ed7. 

I've plans to elaborate project wiki instead of a single long readme file. Please feel free to contribute to the current wiki available here https://github.com/nishad/udemy-dl/wiki, which is incomplete.

**Comment by LukasBombach** [comment]
\o/
